name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  coverage:
    name: Coverage
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: llvm-tools-preview
      - name: Install rustfilt symbol demangler
        run: cargo install rustfilt
      - name: Rerun tests for coverage
        run: cargo test
        env:
          RUSTFLAGS: -Zinstrument-coverage
          LLVM_PROFILE_FILE: "${{ github.workspace }}/test.%p.profraw"
      - name: Merge coverage data
        run: $(rustc --print target-libdir)/../bin/llvm-profdata merge --sparse test.*.profraw -o test.profdata
      - name: Generate coverage report
        run: $(rustc --print target-libdir)/../bin/llvm-cov show -format=html -Xdemangler=rustfilt -show-instantiations -output-dir=./coverage -instr-profile=./test.profdata $(find target/debug/deps -type f -perm -u+x ! -name '*.so')
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
